name: flappy_bird_game
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flame: ^1.10.1  # Atualização para a versão mais recente
  flame_audio: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/player.png
    - assets/images/mapa.jpg
    - assets/images/teste.webp
    - assets/images/pilar.jpg
    - assets/images/Lukewarm_Ocean.webp
    - assets/images/pilar.png
    - assets/images/menu.png

  fonts:
    - family: Mojangles
      fonts:
        - asset: assets/images/fonts/Mojangles.ttf